# This file is automatically generated by the build process when version is
# updated in pyproject.toml.
<<<<<<< HEAD
__version__ = "0.3.15"
=======
__version__ = "0.3.24"
>>>>>>> 6b2f5048a4fcbe02cf4ee79147abc9dcc7c8d99d
